spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
 
server:
  port: 8080
 
mybatis:
  type-aliases-package: com.lyz.makeupMall.domain
  mapper-locations: classpath:mapper/*.xml
